export const NFL_POWER4_SCHOOLS = [
  "Alabama",
  "Arkansas",
  "Auburn",
  "Baylor",
  "Clemson",
  "Florida",
  "Florida State",
  "Georgia",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisville",
  "LSU",
  "Miami (FL)",
  "Michigan",
  "Michigan State",
  "Mississippi State",
  "Missouri",
  "Nebraska",
  "North Carolina",
  "Notre Dame",
  "Ohio State",
  "Oklahoma",
  "Ole Miss",
  "Oregon",
  "Penn State",
  "Purdue",
  "South Carolina",
  "Stanford",
  "Tennessee",
  "Texas",
  "Texas A&M",
  "Texas Tech",
  "UCLA",
  "USC",
  "Virginia",
  "Virginia Tech",
  "Washington",
  "West Virginia",
  "Wisconsin"
];

export const NFL_POWER4_CONFS = [
  "ACC",
  "Big Ten",
  "Big 12",
  "SEC"
];

export const NBA_COLLEGE_SCHOOLS = [
  "Arizona",
  "Duke",
  "Gonzaga",
  "Indiana",
  "Kansas",
  "Kentucky",
  "Michigan",
  "North Carolina",
  "Notre Dame",
  "St John's",
  "Syracuse",
  "Texas",
  "UConn",
  "Villanova"
];

export const NBA_MAJOR_CONFS = [
  "ACC",
  "Big Ten",
  "Big 12",
  "SEC",
  "Big East"
];

export const COLLEGE_NAME_TO_SLUG = {
  "Alabama": "alabama",
  "Arizona": "arizona",
  "Arkansas": "arkansas",
  "Auburn": "auburn",
  "Baylor": "baylor",
  "Boston College": "boston-college",
  "BYU": "byu",
  "Clemson": "clemson",
  "Duke": "duke",
  "Florida": "florida",
  "Florida State": "florida-st",
  "Florida St.": "florida-st",
  "Georgia": "georgia",
  "Georgia Tech": "georgia-tech",
  "Gonzaga": "gonzaga",
  "Houston": "houston",
  "Indiana": "indiana",
  "Illinois": "illinois",
  "Iowa": "iowa",
  "Iowa State": "iowa-st",
  "Kansas": "kansas",
  "Kansas State": "kansas-st",
  "Kent St.": "kent-st",
  "Kentucky": "kentucky",
  "LSU": "lsu",
  "Louisville": "louisville",
  "Marshall": "marshall",
  "Miami": "miami-fl",
  "Miami (FL)": "miami-fl",
  "Miami (OH)": "miami-oh",
  "Michigan": "michigan",
  "Michigan State": "michigan-st",
  "Michigan St.": "michigan-st",
  "Mississippi State": "mississippi-st",
  "Mississippi St.": "mississippi-st",
  "Missouri": "missouri",
  "Nebraska": "nebraska",
  "North Carolina": "north-carolina",
  "Northern Illinois": "northern-illinois",
  "Notre Dame": "notre-dame",
  "Ohio State": "ohio-st",
  "Ohio St.": "ohio-st",
  "Oklahoma": "oklahoma",
  "Ole Miss": "ole-miss",
  "Oregon": "oregon",
  "Penn State": "penn-st",
  "Penn St.": "penn-st",
  "Pittsburgh": "pitt",
  "Purdue": "purdue",
  "South Carolina": "south-carolina",
  "St John's": "st-johns-ny",
  "St. John's": "st-johns-ny",
  "Stanford": "stanford",
  "Syracuse": "syracuse",
  "SMU": "smu",
  "TCU": "tcu",
  "Tennessee": "tennessee",
  "Texas": "texas",
  "Texas A&M": "texas-am",
  "Texas Tech": "texas-tech",
  "UCF": "ucf",
  "UCLA": "ucla",
  "UConn": "uconn",
  "UNC": "north-carolina",
  "USC": "southern-california",
  "Villanova": "villanova",
  "Virginia": "virginia",
  "Virginia Tech": "virginia-tech",
  "Washington": "washington",
  "West Virginia": "west-virginia",
  "Wisconsin": "wisconsin",
  "Wyoming": "wyoming"
};

export function getCollegeSlug(name) {
  return COLLEGE_NAME_TO_SLUG[name] || null;
}

export function getCollegeLogoSrc(name, dark) {
  const slug = getCollegeSlug(name);
  if (!slug) return "";
  return "https://ncaa-api.henrygd.me/logo/" + slug + ".svg" + (dark ? "?dark=true" : "");
}
