export const NFL_POWER4_SCHOOLS = [
  "Alabama",
  "Arkansas",
  "Auburn",
  "Baylor",
  "Clemson",
  "Florida",
  "Florida State",
  "Georgia",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisville",
  "LSU",
  "Miami (FL)",
  "Michigan",
  "Michigan State",
  "Mississippi State",
  "Missouri",
  "Nebraska",
  "North Carolina",
  "Notre Dame",
  "Ohio State",
  "Oklahoma",
  "Ole Miss",
  "Oregon",
  "Penn State",
  "Purdue",
  "South Carolina",
  "Stanford",
  "Tennessee",
  "Texas",
  "Texas A&M",
  "Texas Tech",
  "UCLA",
  "USC",
  "Virginia",
  "Virginia Tech",
  "Washington",
  "West Virginia",
  "Wisconsin"
];

export const NFL_POWER4_CONFS = [
  "ACC",
  "Big Ten",
  "Big 12",
  "SEC"
];

export const NBA_COLLEGE_SCHOOLS = [
  "Arizona",
  "Duke",
  "Gonzaga",
  "Indiana",
  "Kansas",
  "Kentucky",
  "Michigan",
  "North Carolina",
  "Notre Dame",
  "St John's",
  "Syracuse",
  "Texas",
  "UConn",
  "Villanova"
];

export const NBA_MAJOR_CONFS = [
  "ACC",
  "Big Ten",
  "Big 12",
  "SEC",
  "Big East"
];

export const COLLEGE_LOGOS = {
  "Alabama": "/college_logos_zip/College%20Set/Alabama.PNG",
  "Arizona": "/college_logos_zip/College%20Set/Arizona.PNG",
  "Arkansas": "/college_logos_zip/College%20Set/Arkansas.PNG",
  "Auburn": "/college_logos_zip/College%20Set/Auburn.PNG",
  "Baylor": "/college_logos_zip/College%20Set/Baylor.PNG",
  "BYU": "/college_logos_zip/College%20Set/BYU.PNG",
  "Clemson": "/college_logos_zip/College%20Set/Clemson.PNG",
  "Duke": "/college_logos_zip/College%20Set/Duke%20%28basketball%29.PNG",
  "Florida": "/college_logos_zip/College%20Set/Florida.PNG",
  "Florida State": "/college_logos_zip/College%20Set/Florida%20State.PNG",
  "Georgia": "/college_logos_zip/College%20Set/Georgia.PNG",
  "Houston": "/college_logos_zip/College%20Set/Houston%20%28basketball%29.PNG",
  "Indiana": "/college_logos_zip/College%20Set/Indiana%20%28basketball%29.PNG",
  "Iowa": "/college_logos_zip/College%20Set/Iowa.PNG",
  "Iowa State": "/college_logos_zip/College%20Set/Iowa%20State.PNG",
  "Kansas": "/college_logos_zip/College%20Set/Kansas.PNG",
  "Kentucky": "/college_logos_zip/College%20Set/Kentucky.PNG",
  "Louisville": "/college_logos_zip/College%20Set/Louisville.PNG",
  "LSU": "/college_logos_zip/College%20Set/LSU.PNG",
  "Miami": "/college_logos_zip/College%20Set/Miami.PNG",
  "Miami (FL)": "/college_logos_zip/College%20Set/Miami.PNG",
  "Michigan": "/college_logos_zip/College%20Set/Michigan.PNG",
  "Michigan State": "/college_logos_zip/College%20Set/Michigan%20State.PNG",
  "Mississippi State": "/college_logos_zip/College%20Set/Mississippi%20State.PNG",
  "Missouri": "/college_logos_zip/College%20Set/Missouri.PNG",
  "Nebraska": "/college_logos_zip/College%20Set/Nebraska.PNG",
  "North Carolina": "/college_logos_zip/College%20Set/North%20Carolina.PNG",
  "Notre Dame": "/college_logos_zip/College%20Set/Notre%20Dame.PNG",
  "Ohio State": "/college_logos_zip/College%20Set/Ohio%20State.PNG",
  "Oklahoma": "/college_logos_zip/College%20Set/Oklahoma.PNG",
  "Ole Miss": "/college_logos_zip/College%20Set/Ole%20Miss.PNG",
  "Oregon": "/college_logos_zip/College%20Set/Oregon.PNG",
  "Penn State": "/college_logos_zip/College%20Set/Penn%20State.PNG",
  "Purdue": "/college_logos_zip/College%20Set/Purdue.PNG",
  "SMU": "/college_logos_zip/College%20Set/SMU.PNG",
  "South Carolina": "/college_logos_zip/College%20Set/South%20Carolina.PNG",
  "Stanford": "/college_logos_zip/College%20Set/Stanford.PNG",
  "Tennessee": "/college_logos_zip/College%20Set/Tennessee.PNG",
  "Texas": "/college_logos_zip/College%20Set/Texas.PNG",
  "Texas A&M": "/college_logos_zip/College%20Set/Texas%20A%26M.PNG",
  "Texas Tech": "/college_logos_zip/College%20Set/Texas%20Tech.PNG",
  "UCF": "/college_logos_zip/College%20Set/UCF.PNG",
  "UCLA": "/college_logos_zip/College%20Set/UCLA.PNG",
  "UConn": "/college_logos_zip/College%20Set/UConn%20%28basketball%29.PNG",
  "USC": "/college_logos_zip/College%20Set/USC.PNG",
  "Villanova": "/college_logos_zip/College%20Set/Villanova%20%28basketball%29.PNG",
  "Virginia": "/college_logos_zip/College%20Set/Virginia.PNG",
  "Virginia Tech": "/college_logos_zip/College%20Set/Virginia%20Tech.PNG",
  "Washington": "/college_logos_zip/College%20Set/Washington.PNG",
  "West Virginia": "/college_logos_zip/College%20Set/West%20Virginia%20.PNG",
  "Wisconsin": "/college_logos_zip/College%20Set/Wisconsin.PNG"
};
